---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.16.42

platforms:
  - name: ubuntu-14.04
  - name: centos-7.0
  - name: debian-7.8


suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[build-essential]
      - recipe[git]
      - recipe[mecab]

  - name: ipadic
    run_list:
      - recipe[apt]
      - recipe[build-essential]
      - recipe[git]
      - recipe[mecab::ipadic]

  - name: jumandic
    run_list:
      - recipe[apt]
      - recipe[build-essential]
      - recipe[git]
      - recipe[mecab::jumandic]

  - name: unidic
    run_list:
      - recipe[apt]
      - recipe[build-essential]
      - recipe[git]
      - recipe[zip]
      - recipe[mecab::unidic]

  - name: naistjdic
    run_list:
      - recipe[apt]
      - recipe[build-essential]
      - recipe[git]
      - recipe[tar]
      - recipe[mecab::naistjdic]


busser:
  sudo: false
